---
title: "highchart"
author: "Zoe Meers"
date: "13 July 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(highcharter)
data(GII_clean)
```


```{r}

hc <- highchart() %>% 
  hc_chart(GII_clean$Score.Australia
    type = "column"
    ) %>%
  hc_xAxis(
    categories = "1:Institutions":"1.3.3.Ease of paying taxes",
    type = "indicators",
    tickInterval = 30 * 24 * 3600 * 1000,
    labels = list(format = "{value}")
  ) %>% 
  hc_yAxis(
    min = 0,
    labels = list(format = "{value}")
  ) %>%
  hc_add_theme(
    hc_theme_smpl()
    )

hc
```

```{r}
hchart(GII_clean, "column", polar = TRUE, hcaes(x = indicators, y = Score.Australia, group = IO)) %>%
     hc_title(text = "Global Innovation Index - Australia") %>%
  hc_chart(polar=FALSE) %>%
  hc_xAxis(title = list(text = " "), gridLineWidth = 1,
    labels = list(c())) %>%
  hc_yAxis(min=0,max=100,startOnTick=TRUE,
           tickPositions=seq(0,100,by=10))
  
```


```{r}
hchart(GII_clean, "column", polar = TRUE, hcaes(x = indicators, y = Score.US, group = IO)) %>%
     hc_title(text = "Global Innovation Index - US") %>%
  hc_chart(polar=FALSE) %>%
  hc_xAxis(title = list(text = " "), gridLineWidth = 1,
    labels = list(c())) %>%
  hc_yAxis(min=0,max=100,startOnTick=TRUE,
           tickPositions=seq(0,100,by=10))
  
```


```{r, fig.width=10}
library(plotly)

test.dat <- data.frame(xmin=c("6.1.1.Patent applications by origin"), ymin=c(-5,-5), xmax=c("7.Creative outputs"), ymax=c(110,110), col=c("gray"))


p <- ggplot() + geom_rect(data=test.dat, aes(xmin=xmin, ymin=ymin, xmax=xmax, ymax=ymax, group=col), alpha=0.03, fill=test.dat$col) +
  geom_bar(data=GII_clean, aes(x=indicators, y=Score.Australia, fill=IO), colour="black", stat="identity", position=position_dodge(),size=.3) + theme_bw() + xlab("Indicator") + ylab("Score (Out of 100)") + theme(
  axis.text.x = element_blank(),
  axis.ticks = element_blank(), legend.position = "bottom")





# Set axis labels
   # ggtitle("Average bill for 2 people") +     # Set title
   # theme_bw()

p <- ggplotly(p)


p




```







```{r}
a <- ggplot() + geom_rect(data=GII_clean, aes(ymax=Inf, ymin=-Inf, xmin="6.Knowledge and technology outputs", xmax="7.3.4.Video uploads on YouTube"), fill="#d8161688", alpha=0.008)+
  geom_bar(data=GII_clean, aes(x=indicators, y=Score.US, fill=IO), colour="black", stat="identity", position=position_dodge(),size=.3) + theme_bw() + xlab("Indicator") + ylab("Score (Out of 100)") + theme(
  axis.text.x = element_blank(),
  axis.ticks = element_blank(), legend.position = "bottom")





# Set axis labels
   # ggtitle("Average bill for 2 people") +     # Set title
   # theme_bw()

a <- ggplotly(p)


a
```






