var inidcators = ["indicators" "Rank","Score","SWAus","IO","subind"]

"2","Global Innovation IndexNA",23,51.8,NA,NA,NA
"3","Innovation Efficiency RatioNA",76,0.6,"Weakness",NA,NA
"4","Innovation Input Sub-indexNA",12,64.6,NA,NA,NA
"5","Innovation Output Sub-indexNA",30,39.1,NA,NA,NA



var index = [
{name: "1.Institutions", Rank: 14, Score: 87.4, SWAus: NA, IO: "institutions", subind: NA},
{name: "1.1.Political environment", Rank: 17, Score: 83.9,SWAus: NA, IO: "institutions", subind: "political env"},
{name: "1.1.1.Political stability and absence of violence/terrorism", Rank: 24, Score: 85.7, SWAus: NA, IO: "institutions", subind: "political env"},
{name: "1.1.2.Government effectiveness", Rank: 15, Score: 82.2, SWAus:NA, IO: "institutions", subind:"political env"},
{name: "1.2.Regulatory environment", Rank: 11, Score: 91.2, SWAus: NA, IO: "institutions", subind: "regulatory env"},
{name: "1.2.1.Regulatory quality", Rank: 8, Score: 88, SWAus: NA, IO: "institutions", subind: "regulatory env"}
{name: "1.2.2.Rule of law", Rank: 13, Score: 92.7, SWAus: NA, IO: "institutions", subind: "regulatory env"},
{name: "1.2.3.Cost of redundancy dismissal", Rank: 43, Score: 92.1, SWAus: NA, IO: "institutions",subind: "regulatory env"},
{name: "1.3.Business environment", Rank: 16, Score: 86.9, SWAus: NA, IO: "institutions", subind: "business env"},
{name: "1.3.1.Ease of starting a business", Rank: 7, Score: 96.5, SWAus: "Strength", IO: "institutions", subind: "business env"},
{name: "1.3.2.Ease of resolving insolvency", Rank: 20, Score: 78.7, SWAus: NA, IO: "institutions", subind: "business env"},
{name: "1.3.3.Ease of paying taxes", Rank: 23, Score: 85.6, SWAus: NA, IO: "institutions", subind: "business env"},
{name: "2.Human capital and research",Rank: 9, Score: 60.2, SWAus: NA, IO: "human capital", subind: NA},
{name: "2.1.Education", Rank: 26, Score: 58.6, SWAus: NA, IO: "human capital", subind: "education"},
{name: "2.1.1.Expenditure on education", Rank: 41, Score: 48.9, SWAus: NA, IO: "human capital", subind: "education"},
{name: "2.1.2.Government expenditure on education per pupil, secondary", Rank: 66, Score: 17.7, SWAus: "Weakness", IO: "human capital", subind: "education"},
{name: "2.1.3.School life expectancy", Rank: 1, Score: 100, SWAus: "Strength", IO: "human capital", subind: "education"},
{name: "2.1.4.Assessment in reading, mathematics, and science", Rank: 19, Score: 77.1, SWAus: NA, IO: "human capital", subind: "education"},
{name: "2.1.5.Pupil-teacher ratio, secondary", Rank: NA, Score: NA, SWAus: NA, IO: "human capital", subind: "education"},
{name: "2.2.Tertiary education", Rank: 10, Score:58.1, SWAus: NA, IO: "human capital", subind: "tertiary education"},
{name: "2.2.1.Tertiary enrolment", Rank: 3, Score: 79.2, SWAus: "Strength", IO: "human capital", subind:"tertiary education"},
{name: "2.2.2.Graduates in science and engineering", Rank: 79,Score: 28.9,SWAus:"Weakness",IO:"human capital", subind:"tertiary education"},
{name: "2.2.3.Tertiary level inbound mobility", Rank: 6, Score: 95.5, SWAus: "Strength", IO: "human capital", subind: "tertiary education"},
{name: "2.3.Research and development (R&D)", Rank: 13, Score: 64, SWAus: NA, IO: "human capital", subind: "research and development"},
{name: "2.3.1.Researchers", Rank: 15, Score: 54.8, SWAus: NA, IO: "human capital", subind: "research and development"},
{name: "2.3.2.Gross expenditure on R&D (GERD)", Rank: 16, Score: 50.9, SWAus: NA, IO: "human capital", subind: "research and development"},
{name: "2.3.3.Global R&D companies, average expenditure top 3", Rank: 19, Score: 68.6, SWAus: NA, IO: "human capital", subind: "research and development"},
{name: "2.3.4.QS university ranking average score top 3 universities", Rank: 7, Score: 81.6, SWAus: "Strength", IO: "human capital", subind: "research and development"},
{name: "3.Infrastructure", Rank: 7, Score: 64.8, SWAus: "Strength", IO: "infrastructure", subind: NA},
{name: "3.1.Information and communication technologies (ICTs)", Rank: 4, Score: 88.9, SWAus: "Strength", IO: "infrastructure", subind: "ICT"},
{name: "3.1.1.ICT access", Rank: 20, Score: 82.3, SWAus: NA, IO: "infrastructure", subind: "ICT"},
{name: "3.1.2.ICT use",15,77,NA,"infrastructure","ICT"},
{name: "3.1.3.Government's online service",2,97.8,"Strength","infrastructure","ICT"},
{name: "3.1.4.Online e-participation",2,98.3,"Strength","infrastructure","ICT"},
{name: "3.2.General infrastructure",12,53.7,NA,"infrastructure","general infrastructure"},
{name: "3.2.1.Electricity output",13,37.3,NA,"infrastructure","general infrastructure"},
{name: "3.2.2.Logistics performance",19,80,NA,"infrastructure","general infrastructure"},
{name: "3.2.3.Gross capital formation",45,48.7,NA,"infrastructure","general infrastructure"},
{name: "3.3.Ecological sustainability",41,51.8,NA,"infrastructure","ecological sustainability"},
{name: "3.3.1.GDP per unit of energy use",67,29.2,"Weakness","infrastructure","ecological sustainability"},
{name: "3.3.2.Environmental performance",13,87.2,NA,"infrastructure","ecological sustainability"},
{name: "3.3.3.ISO 14001 environmental certificates",26,26.1,NA,"infrastructure","ecological sustainability"},
{name: "4.Market sophistication",9,65.3,NA,"market",NA},
{name: "4.1.Credit",5,72.5,"Strength","market","credit"},
{name: "4.1.1.Ease of getting credit",5,90,"Strength","market","credit"},
{name: "4.1.2.Domestic credit to private sector",13,55.1,NA,"market","credit"},
{name: "4.1.3.Microfinance institutions' gross loan portfolio",NA,NA,NA,"market","credit"},
{name: "4.2.Investment",40,45.2,NA,"market","investment"},
{name: "4.2.1.Ease of protecting minority investors",62,58.3,NA,"market","investment"},
{name: "4.2.2.Market capitalization",13,37.9,NA,"market","investment"},
{name: "4.2.3.Venture capital deals",22,26.3,NA,"market","investment"},
{name: "4.3.Trade, competition, & market scale",13,78.2,NA,"market","trade, competition, and market scale"},
{name: "4.3.1.Applied tariff rate, weighted mean",53,89,NA,"market","trade, competition, and market scale"},
{name: "4.3.2.Intensity of local competition",6,81.9,"Strength","market","trade, competition, and market scale"},
{name: "4.3.3.Domestic market scale",19,71,NA,"market","trade, competition, and market scale"},
{name: "5.Business sophistication",27,45.4,NA,"business",NA},
{name: "5.1.Knowledge workers",10,67.5,NA,"business","knowledge workers"},
{name: "5.1.1.Employment in knowledge-intensive services",13,78.8,NA,"business","knowledge workers"},
{name: "5.1.2.Firms offering formal training",NA,NA,NA,"business","knowledge workers"},
{name: "5.1.3.GERD performed by business enterprise",17,33.7,NA,"business","knowledge workers"},
{name: "5.1.4.GERD financed by business enterprise",9,79.4,NA,"business","knowledge workers"},
{name: "5.1.5.Females employed with advanced degrees",16,66.8,NA,"business","knowledge workers"},
{name: "5.2.Innovation linkages",52,32,NA,"business","innovation linkages"},
{name: "5.2.1.University/industry research collaboration",32,54.5,NA,"business","innovation linkages"},
{name: "5.2.2.State of cluster development",42,49.6,NA,"business","innovation linkages"},
{name: "5.2.3.GERD financed by abroad",80,2.7,"Weakness","business","innovation linkages"},
{name: "5.2.4.Joint venture/strategic alliance deals",7,53.9,NA,"business","innovation linkages"},
{name: "5.2.5.Patent families filed in at least two offices",28,11.1,NA,"business","innovation linkages"},
{name: "5.3.Knowledge absorption",48,36.6,NA,"business","knowledge absorption"},
{name: "5.3.1.Intellectual property payments",20,38.9,NA,"business","knowledge absorption"},
{name: "5.3.2.High-tech imports",28,40.5,NA,"business","knowledge absorption"},
{name: "5.3.3.ICT services imports",69,17.1,"Weakness","business","knowledge absorption"},
{name: "5.3.4.Foreign direct investment, net inflows",53,54.5,NA,"business","knowledge absorption"},
{name: "5.3.5.Research talent in business enterprise",46,33.2,"Weakness","business","knowledge absorption"},
{name: "6.Knowledge and technology outputs",34,32.1,NA,"knowledge",NA},
{name: "6.1.Knowledge creation",25,34.3,NA,"knowledge","knowledge creation"},
{name: "6.1.1.Patent applications by origin",45,10.7,NA,"knowledge","knowledge creation"},
{name: "6.1.2.PCT international applications by origin",22,20.6,NA,"knowledge","knowledge creation"},
{name: "6.1.3.Utility model applications by origin",27,21.4,NA,"knowledge","knowledge creation"},
{name: "6.1.4.Scientific and technical publications",9,68.3,NA,"knowledge","knowledge creation"},
{name: "6.1.5.Citable documents H index",10,63.5,NA,"knowledge","knowledge creation"},
{name: "6.2.Knowledge impact",19,44,NA,"knowledge","knowledge impact"},
{name: "6.2.1.Growth rate of GDP per person engaged",62,48.1,"Weakness","knowledge","knowledge impact"},
{name: "6.2.2.New business density",5,86.4,"Strength","knowledge","knowledge impact"},
{name: "6.2.3.Total computer software spending",51,25.2,NA,"knowledge","knowledge impact"},
{name: "6.2.4.ISO 9001 quality certificates",32,19.6,NA,"knowledge","knowledge impact"},
{name: "6.2.5.High-tech and medium high-tech output",49,36.6,NA,"knowledge","knowledge impact"},
{name: "6.3.Knowledge diffusion",96,17.9,"Weakness","knowledge","knowledge diffusion"},
{name: "6.3.1.Intellectual property receipts",31,13.9,NA,"knowledge","knowledge diffusion"},
{name: "6.3.2.High-tech exports",55,6.9,NA,"knowledge","knowledge diffusion"},
{name: "6.3.3.ICT services exports",89,7.3,"Weakness","knowledge","knowledge diffusion"},
{name: "6.3.4." "Foreign direct investment", "net outflows",91,30.6,"Weakness","knowledge","knowledge diffusion"},
{name: "7." "Creative outputs",24,46.1,NA,"creativity",NA},
{name: "7.1.Intangible assets",36,50.3,NA,"creativity","intangible assets"},
{name: "7.1.1.Trademark application class count by origin",25,36.1,NA,"creativity","intangible assets"},
{name: "7.1.2.Industrial designs by origin",41,13.2,NA,"creativity","intangible assets"},
{name: "7.1.3.ICTs and business model creation",35,68.5,NA,"creativity","intangible assets"},
{name: "7.1.4.ICTs and organizational model creation",28,64.8,NA,"creativity","intangible assets"},
{name: "7.2.Creative goods and services",38,27.4,NA,"creativity","creative goods and services"},
{name: "7.2.1.Cultural and creative services exports",38,16,NA,"creativity","creative goods and services"},
{name: "7.2.2.National feature films produced",61,7.1,"Weakness","creativity","creative goods and services"},
{name: "7.2.3.Global entertainment and media market",8,63.9,NA,"creativity","creative goods and services"},
{name: "7.2.4.Printing and publishing output",19,30.7,NA,"creativity","creative goods and services"},
{name: "7.2.5.Creative goods exports",48,21.6,NA,"creativity","creative goods and services"},
{name: "7.3.Online creativity",12,56.2,NA,"creativity","online creativity"},
{name: "7.3.1.Generic top-level domains (gTLDs)",9,63.6,NA,"creativity","online creativity"},
{name: "7.3.2.Country-code top-level domains (ccTLDs)",14,52.8,NA,"creativity","online creativity"},
{name: "7.3.3.Wikipedia yearly edits",24,63.8,NA,"creativity","online creativity"},
{name: "7.3.4.Video uploads on YouTube",23,44.8,NA,"creativity","online creativity"},
