---
title: "highchart"
author: "Zoe Meers"
date: "13 July 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(highcharter)
data(GII_clean)
```

```{r}
GII_clean_index <- slice(GII_clean, 7:115) %>%
  mutate(GII_clean_index$S.W.Aus, ifelse(is.na(S.W.Aus),"N/A",S.W.Aus)) %>%
  mutate(GII_clean_index$S.W.US, ifelse(is.na(S.W.US),"N/A",S.W.US))
```


```{r}

x <- c("Score:", "Rank:")
y <- c("{Score.Australia}", "{Rank.Indicator.Aus}")
tooltip_table(x, y)


hchart(GII_clean_index, "column",  hcaes(x = indicators, y = Score.Australia, group = IO)) %>%
     hc_title(text = " 2017 Global Innovation Index - Australia") %>%
  hc_xAxis(title = list(text = " "), gridLineWidth = 0,
    labels = list(c())) %>%
  hc_yAxis(title = list(text = "Score (out of 100)"), min=0,max=100,startOnTick=TRUE,
           tickPositions=seq(0,100,by=10))  %>%
  hc_add_theme(hc_theme_smpl()) #%>%
  #hc_tooltip(tooltip_table(x, y))
  
```



```{r, fig.height=20}


 a <- hchart(GII_clean_index, "column",  hcaes(x = indicators, y = Score.Australia, group = IO), pointWidth=8) %>%
     hc_title(text = "2017 Global Innovation Index - Australia") %>%
  hc_subtitle(text="Rank: 23. Score: 51.8. Score is the average of innovation inputs and innovation outputs") %>%
  hc_xAxis(title = list(text = " "), gridLineWidth = 0,
    labels = list(c())) %>% #, plot.Bands(list=list(from = 3, to = 5, color = "gray"))) %>%
  hc_yAxis(title = list(text = "Score (out of 100)"),min=0,max=100,startOnTick=TRUE,
           tickPositions=seq(0,100,by=10)) %>% hc_add_theme(hc_theme_smpl())
#a <- a %>%
 # hc_add_series(GII_clean_index, type = "column", hcaes(x= `indicators`, y=`Score.US`), color = 'url(#highcharts-default-pattern-0)', pointWidth=5, name="US Score", align="center")

a
```


```{r, fig.height=20}


 b <- hchart(GII_clean_index, "column",  hcaes(x = indicators, y = Score.US, group = IO), pointWidth=8) %>%
  hc_subtitle(text="Rank: 4. Score:61.4. Score is the average of innovation inputs and innovation outputs") %>%
     hc_title(text = "2017 Global Innovation Index - US") %>%
  hc_xAxis(title = list(text = " "), gridLineWidth = 0,
    labels = list(c())) %>% #, plot.Bands(list=list(from = 3, to = 5, color = "gray"))) %>%
  hc_yAxis(title = list(text = "Score (out of 100)"),min=0,max=100,startOnTick=TRUE,
           tickPositions=seq(0,100,by=10)) %>% hc_add_theme(hc_theme_smpl())
#b <- b %>%
 # hc_add_series(GII_clean_index, type = "column", hcaes(x= `indicators`, y=`Score.US`), color = 'url(#highcharts-default-pattern-0)', pointWidth=5, name="US Score", align="center")

b
```

```{r}

```

