var inidcators = [
{name: "Global Innovation Index", Rank: 23, Score: 51.8}, 
{name: "Innovation Efficiency Ratio", Rank: 76, Score: 0.6},
{name: "Innovation Input Sub-index", Rank: 12, Score: 64.6},
{name: "Innovation Output Sub-index", Rank: 30, Score: 39.1}
];


var index = [
{name: "1.Institutions", Rank: 14, Score: 87.4, SWAus: NA, IO: "institutions", subind: NA, innov:"input"},
{name: "1.1.Political environment", Rank: 17, Score: 83.9,SWAus: NA, IO: "institutions", subind: "political env", innov:"input"},
{name: "1.1.1.Political stability and absence of violence/terrorism", Rank: 24, Score: 85.7, SWAus: NA, IO: "institutions", subind: "political env", innov:"input"},
{name: "1.1.2.Government effectiveness", Rank: 15, Score: 82.2, SWAus:NA, IO: "institutions", subind:"political env", innov:"input"},
{name: "1.2.Regulatory environment", Rank: 11, Score: 91.2, SWAus: NA, IO: "institutions", subind: "regulatory env", innov:"input"},
{name: "1.2.1.Regulatory quality", Rank: 8, Score: 88, SWAus: NA, IO: "institutions", subind: "regulatory env", innov:"input"}
{name: "1.2.2.Rule of law", Rank: 13, Score: 92.7, SWAus: NA, IO: "institutions", subind: "regulatory env", innov:"input"},
{name: "1.2.3.Cost of redundancy dismissal", Rank: 43, Score: 92.1, SWAus: NA, IO: "institutions",subind: "regulatory env", innov:"input"},
{name: "1.3.Business environment", Rank: 16, Score: 86.9, SWAus: NA, IO: "institutions", subind: "business env", innov:"input"},
{name: "1.3.1.Ease of starting a business", Rank: 7, Score: 96.5, SWAus: "Strength", IO: "institutions", subind: "business env", innov:"input"},
{name: "1.3.2.Ease of resolving insolvency", Rank: 20, Score: 78.7, SWAus: NA, IO: "institutions", subind: "business env", innov:"input"},
{name: "1.3.3.Ease of paying taxes", Rank: 23, Score: 85.6, SWAus: NA, IO: "institutions", subind: "business env", innov:"input"},
{name: "2.Human capital and research",Rank: 9, Score: 60.2, SWAus: NA, IO: "human capital", subind: NA, innov:"input"},
{name: "2.1.Education", Rank: 26, Score: 58.6, SWAus: NA, IO: "human capital", subind: "education", innov:"input"},
{name: "2.1.1.Expenditure on education", Rank: 41, Score: 48.9, SWAus: NA, IO: "human capital", subind: "education", innov:"input"},
{name: "2.1.2.Government expenditure on education per pupil, secondary", Rank: 66, Score: 17.7, SWAus: "Weakness", IO: "human capital", subind: "education", innov:"input"},
{name: "2.1.3.School life expectancy", Rank: 1, Score: 100, SWAus: "Strength", IO: "human capital", subind: "education", innov:"input"},
{name: "2.1.4.Assessment in reading, mathematics, and science", Rank: 19, Score: 77.1, SWAus: NA, IO: "human capital", subind: "education", innov:"input"},
{name: "2.1.5.Pupil-teacher ratio, secondary", Rank: NA, Score: NA, SWAus: NA, IO: "human capital", subind: "education", innov:"input"},
{name: "2.2.Tertiary education", Rank: 10, Score:58.1, SWAus: NA, IO: "human capital", subind: "tertiary education", innov:"input"},
{name: "2.2.1.Tertiary enrolment", Rank: 3, Score: 79.2, SWAus: "Strength", IO: "human capital", subind:"tertiary education", innov:"input"},
{name: "2.2.2.Graduates in science and engineering", Rank: 79,Score: 28.9,SWAus:"Weakness",IO:"human capital", subind:"tertiary education", innov:"input"},
{name: "2.2.3.Tertiary level inbound mobility", Rank: 6, Score: 95.5, SWAus: "Strength", IO: "human capital", subind: "tertiary education", innov:"input"},
{name: "2.3.Research and development (R&D)", Rank: 13, Score: 64, SWAus: NA, IO: "human capital", subind: "research and development", innov:"input"},
{name: "2.3.1.Researchers", Rank: 15, Score: 54.8, SWAus: NA, IO: "human capital", subind: "research and development", innov:"input"},
{name: "2.3.2.Gross expenditure on R&D (GERD)", Rank: 16, Score: 50.9, SWAus: NA, IO: "human capital", subind: "research and development", innov:"input"},
{name: "2.3.3.Global R&D companies, average expenditure top 3", Rank: 19, Score: 68.6, SWAus: NA, IO: "human capital", subind: "research and development", innov:"input"},
{name: "2.3.4.QS university ranking average score top 3 universities", Rank: 7, Score: 81.6, SWAus: "Strength", IO: "human capital", subind: "research and development", innov:"input"},
{name: "3.Infrastructure", Rank: 7, Score: 64.8, SWAus: "Strength", IO: "infrastructure", subind: NA, innov:"input"},
{name: "3.1.Information and communication technologies (ICTs)", Rank: 4, Score: 88.9, SWAus: "Strength", IO: "infrastructure", subind: "ICT", innov:"input"},
{name: "3.1.1.ICT access", Rank: 20, Score: 82.3, SWAus: NA, IO: "infrastructure", subind: "ICT", innov:"input"},
{name: "3.1.2.ICT use", Rank: 15, Score: 77, SWAus: NA, IO: "infrastructure", subind: "ICT", innov:"input"},
{name: "3.1.3.Government's online service", Rank: 2, Score: 97.8, SWAus: "Strength", IO: "infrastructure", subind: "ICT", innov:"input"},
{name: "3.1.4.Online e-participation", Rank: 2, Score: 98.3, SWAus: "Strength", IO:"infrastructure", subind:"ICT", innov:"input"},
{name: "3.2.General infrastructure", Rank: 12, Score: 53.7, SWAus: NA, IO: "infrastructure", subind: "general infrastructure", innov:"input"},
{name: "3.2.1.Electricity output", Rank: 13, Score: 37.3, SWAus: NA, IO: "infrastructure", subind: "general infrastructure", innov:"input"},
{name: "3.2.2.Logistics performance", Rank: 19, Score: 80, SWAus: NA, IO: "infrastructure", subind: "general infrastructure", innov:"input"},
{name: "3.2.3.Gross capital formation", Rank: 45, Score: 48.7,SWAus: NA, IO: "infrastructure", subind: "general infrastructure", innov:"input"},
{name: "3.3.Ecological sustainability", Rank: 41, Score: 51.8, SWAus: NA, IO: "infrastructure", subind: "ecological sustainability", innov:"input"},
{name: "3.3.1.GDP per unit of energy use", Rank: 67, Score: 29.2, SWAus: "Weakness", IO: "infrastructure", subind: "ecological sustainability", innov:"input"},
{name: "3.3.2.Environmental performance", Rank: 13, Score: 87.2, SWAus: NA, IO: "infrastructure", subind: "ecological sustainability", innov:"input"},
{name: "3.3.3.ISO 14001 environmental certificates", Rank: 26, Score: 26.1, SWAus: NA, IO: "infrastructure", subind: "ecological sustainability", innov:"input"},
{name: "4.Market sophistication", Rank: 9, Score: 65.3, SWAus: NA, IO: "market",subind: NA, innov:"input"},
{name: "4.1.Credit", Rank: 5, Score: 72.5, SWAus: "Strength", IO: "market", subind: "credit", innov:"input"},
{name: "4.1.1.Ease of getting credit", Rank: 5, Score: 90, SWAus: "Strength", IO: "market", subind: "credit", innov:"input"},
{name: "4.1.2.Domestic credit to private sector", Rank: 13, Score: 55.1, SWAus: NA, IO: "market", subind: "credit", innov:"input"},
{name: "4.1.3.Microfinance institutions' gross loan portfolio", Rank: NA, Score: NA, SWAus: NA, IO: "market", subind: "credit", innov:"input"},
{name: "4.2.Investment", Rank: 40, Score: 45.2, SWAus: NA, IO: "market", subind: "investment", innov:"input"},
{name: "4.2.1.Ease of protecting minority investors", Rank: 62, Score: 58.3, SWAus: NA, IO: "market", subind: "investment", innov:"input"},
{name: "4.2.2.Market capitalization", Rank: 13, Score: 37.9, SWAus: NA, IO: "market", subind: "investment", innov:"input"},
{name: "4.2.3.Venture capital deals", Rank: 22, Score: 26.3, SWAus: NA, IO: "market", subind: "investment", innov:"input"},
{name: "4.3.Trade, competition, & market scale", Rank: 13, Score: 78.2, SWAus: NA, IO: "market", subind: "trade, competition, and market scale", innov:"input"},
{name: "4.3.1.Applied tariff rate, weighted mean", Rank: 53, Score: 89, SWAus: NA, IO: "market", subind: "trade, competition, and market scale", innov:"input"},
{name: "4.3.2.Intensity of local competition", Rank: 6, Score: 81.9, SWAus: "Strength", IO: "market", subind: "trade, competition, and market scale", innov:"input"},
{name: "4.3.3.Domestic market scale", Rank: 19, Score: 71, SWAus: NA, IO: "market", subind: "trade, competition, and market scale", innov:"input"},
{name: "5.Business sophistication", Rank: 27, Score: 45.4, SWAus: NA, IO: "business", subind: NA, innov:"input"},
{name: "5.1.Knowledge workers", Rank: 10, Score: 67.5, SWAus:NA, IO: "business", subind: "knowledge workers", innov:"input"},
{name: "5.1.1.Employment in knowledge-intensive services", Rank: 13, Score: 78.8, SWAus: NA, IO: "business", subind: "knowledge workers", innov:"input"},
{name: "5.1.2.Firms offering formal training", Rank: NA, Score: NA, SWAus: NA, IO: "business", subind: "knowledge workers", innov:"input"},
{name: "5.1.3.GERD performed by business enterprise", Rank: 17, Score: 33.7, SWAus: NA, IO: "business", subind: "knowledge workers", innov:"input"},
{name: "5.1.4.GERD financed by business enterprise", Rank: 9, Score: 79.4, SWAus: NA, IO: "business", subind: "knowledge workers", innov:"input"},
{name: "5.1.5.Females employed with advanced degrees", Rank: 16, Score: 66.8, SWAus: NA, IO: "business", subind: "knowledge workers", innov:"input"},
{name: "5.2.Innovation linkages", Rank: 52, Score: 32, SWAus: NA, IO:"business", subind: "innovation linkages", innov:"input"},
{name: "5.2.1.University/industry research collaboration", Rank: 32, Score: 54.5, SWAus: NA, IO: "business", subind: "innovation linkages", innov:"input"},
{name: "5.2.2.State of cluster development", Rank: 42, Score: 49.6, SWAus: NA, IO: "business", subind: "innovation linkages", innov:"input"},
{name: "5.2.3.GERD financed by abroad", Rank: 80, Score: 2.7, SWAus: "Weakness", IO: "business", subind: "innovation linkages", innov:"input"},
{name: "5.2.4.Joint venture/strategic alliance deals", Rank: 7, Score: 53.9, SWAus: NA, IO: "business", subind: "innovation linkages", innov:"input"},
{name: "5.2.5.Patent families filed in at least two offices", Rank: 28, Score: 11.1, SWAus: NA, IO: "business", subind: "innovation linkages", innov:"input"},
{name: "5.3.Knowledge absorption", Rank: 48, Score: 36.6, SWAus: NA, IO: "business", subind: "knowledge absorption", innov:"input"},
{name: "5.3.1.Intellectual property payments",Rank: 20, Score: 38.9, SWAus: NA, IO: "business", subind:"knowledge absorption", innov:"input"},
{name: "5.3.2.High-tech imports", Rank: 28, Score: 40.5, SWAus: NA, IO: "business", subind: "knowledge absorption", innov:"input"},
{name: "5.3.3.ICT services imports", Rank: 69, Score: 17.1, SWAus: "Weakness", IO: "business", subind: "knowledge absorption", innov:"input"},
{name: "5.3.4.Foreign direct investment, net inflows", Rank: 53, Score: 54.5, SWAus: NA, IO: "business", subind: "knowledge absorption", innov:"input"},
{name: "5.3.5.Research talent in business enterprise", Rank: 46, Score: 33.2, SWAus: "Weakness", IO: "business", subind: "knowledge absorption", innov:"input"},
{name: "6.Knowledge and technology outputs", Rank: 34, Score: 32.1, SWAus: NA, IO: "knowledge", subind: NA, innov: "output"},
{name: "6.1.Knowledge creation", Rank: 25, Score: 34.3, SWAus: NA, IO: "knowledge", subind: "knowledge creation", innov: "output"},
{name: "6.1.1.Patent applications by origin", Rank: 45, Score: 10.7, SWAus: NA, IO: "knowledge", subind: "knowledge creation", innov: "output"},
{name: "6.1.2.PCT international applications by origin", Rank: 22, Score: 20.6, SWAus: NA, IO: "knowledge", subind: "knowledge creation", innov: "output"},
{name: "6.1.3.Utility model applications by origin", Rank: 27, Score: 21.4, SWAus: NA, IO: "knowledge", subind: "knowledge creation", innov: "output"},
{name: "6.1.4.Scientific and technical publications", Rank: 9, Score: 68.3, SWAus: NA, IO: "knowledge", subind: "knowledge creation", innov: "output"},
{name: "6.1.5.Citable documents H index", Rank: 10, Score: 63.5, SWAus: NA, IO: "knowledge", subind: "knowledge creation", innov: "output"},
{name: "6.2.Knowledge impact", Rank: 19, Score: 44, SWAus: NA, IO: "knowledge", subind: "knowledge impact", innov: "output"},
{name: "6.2.1.Growth rate of GDP per person engaged", Rank: 62, Score: 48.1, SWAus: "Weakness", IO: "knowledge", subind: "knowledge impact", innov: "output"},
{name: "6.2.2.New business density", Rank: 5, Score: 86.4, SWAus: "Strength", IO: "knowledge", subind: "knowledge impact", innov: "output"},
{name: "6.2.3.Total computer software spending", Rank: 51, Score: 25.2, SWAus: NA, IO: "knowledge", subind: "knowledge impact", innov: "output"},
{name: "6.2.4.ISO 9001 quality certificates", Rank: 32, Score: 19.6, SWAus: NA, IO: "knowledge", subind: "knowledge impact", innov: "output"},
{name: "6.2.5.High-tech and medium high-tech output", Rank: 49, Score: 36.6, SWAus: NA, IO: "knowledge", subind: "knowledge impact", innov: "output"},
{name: "6.3.Knowledge diffusion", Rank: 96, Score: 17.9, SWAus: "Weakness", IO: "knowledge", subind: "knowledge diffusion", innov: "output"},
{name: "6.3.1.Intellectual property receipts", Rank: 31, Score: 13.9, SWAus: NA, IO: "knowledge", subind: "knowledge diffusion", innov: "output"},
{name: "6.3.2.High-tech exports", Rank: 55, Score: 6.9, SWAus: NA, IO:"knowledge", subind: "knowledge diffusion", innov: "output"},
{name: "6.3.3.ICT services exports", Rank: 89, Score:7.3, SWAus:"Weakness", IO: "knowledge", subind: "knowledge diffusion", innov: "output"},
{name: "6.3.4.Foreign direct investment - net outflows", Rank: 91, Score: 30.6, SWAus: "Weakness", IO: "knowledge", subind: "knowledge diffusion", innov: "output"},
{name: "7.Creative outputs", Rank: 24, Score: 46.1, SWAus: NA, IO: "creativity", subind: NA, innov: "output"},
{name: "7.1.Intangible assets", Rank: 36, Score: 50.3, SWAus: NA, IO: "creativity", subind: "intangible assets", innov: "output"},
{name: "7.1.1.Trademark application class count by origin", Rank: 25, Score: 36.1, SWAus: NA, IO: "creativity", subind: "intangible assets", innov: "output"},
{name: "7.1.2.Industrial designs by origin", Rank: 41, Score: 13.2, SWAus: NA, IO: "creativity", subind: "intangible assets", innov: "output"},
{name: "7.1.3.ICTs and business model creation", Rank: 35, Score: 68.5, SWAus: NA, IO: "creativity", subind: "intangible assets", innov: "output"},
{name: "7.1.4.ICTs and organizational model creation", Rank: 28, Score: 64.8, SWAus: NA, IO: "creativity", subind: "intangible assets", innov: "output"},
{name: "7.2.Creative goods and services", Rank: 38, Score: 27.4, SWAus: NA, IO: "creativity", subind: "creative goods and services", innov: "output"},
{name: "7.2.1.Cultural and creative services exports", Rank: 38, Score: 16, SWAus: NA, IO: "creativity", subind: "creative goods and services", innov: "output"},
{name: "7.2.2.National feature films produced", Rank: 61, Score: 7.1, SWAus: "Weakness", IO: "creativity", subind: "creative goods and services", innov: "output"},
{name: "7.2.3.Global entertainment and media market", Rank: 8, Score: 63.9, SWAus:NA, IO: "creativity", subind: "creative goods and services", innov: "output"},
{name: "7.2.4.Printing and publishing output", Rank: 19, Score: 30.7, SWAus:NA, IO: "creativity", subind: "creative goods and services", innov: "output"},
{name: "7.2.5.Creative goods exports", Rank: 48, Score: 21.6, SWAus: NA, IO: "creativity", subind: "creative goods and services", innov: "output"},
{name: "7.3.Online creativity", Rank: 12, Score: 56.2, SWAus: NA, IO: "creativity",subind: "online creativity", innov: "output"},
{name: "7.3.1.Generic top-level domains (gTLDs)", Rank: 9, Score: 63.6, SWAus: NA, IO: "creativity", subind: "online creativity", innov: "output"},
{name: "7.3.2.Country-code top-level domains (ccTLDs)", Rank: 14, Score: 52.8, SWAus: NA, IO: "creativity", subind: "online creativity", innov: "output"},
{name: "7.3.3.Wikipedia yearly edits", Rank: 24, Score: 63.8, SWAus: NA, IO: "creativity", subind: "online creativity", innov: "output"},
{name: "7.3.4.Video uploads on YouTube", Rank: 23, Score: 44.8, SWAus: NA, IO: "creativity", subind: "online creativity", innov: "output"}
];


